### ISSUE TITLE
Lepší menu

### ISSUE THREAD

**Issue by rrrajsky** [rrrajsky/WASkupinovka#2]
Položky menu jsou na sebe namačkané a celkově je nepřehledné.

**Comment by notnguyen** [comment]
Aby položky menu nebyli tak na sebe namačkané. Navrhl jsem přidání větší mezery a vnitřní odsazení položek pro lepší přehlednost.

Tyto úpravy jsem udělal v souboru ***style.css***:

```css
#basic_wrapper .bn49,
#basic_filter input,
#delete-btn,
#export-btn,
#basic_wrapper select,
#basic_wrapper option,
#basic_wrapper label {
  border: 0;
  text-align: center;
  padding: 8px;
  margin: 0px 5px;                 /* Přidává mezery kolem položek menu */
  font-size: 14px;
  max-height: 50px;
  color: #ffffff;
  background-color: #36a2eb;
  border-radius: 8px;
  font-family: "proxima-nova-soft", sans-serif;
  font-weight: 600;
  text-decoration: none;
  transition: box-shadow 200ms ease-out;
}

@media screen and (max-width: 640px) {
   .topnav #myLinks label,
   .topnav #myLinks .bn49 {
   width: 50%;
 }
}

```
