### ISSUE TITLE
Tlačítko zavřít plovoucí

### ISSUE THREAD

**Issue by rrrajsky** [rrrajsky/WASkupinovka#4]
Tlačítko zavřít při editaci firmy by mělo být plovoucí a nevadit

**Comment by novotny13** [comment]
Pro vytvoření plovoucího tlačítka, které nepřekáží jsem udělal tyto úpravy v souboru **style.css:**


Pro @media only screen and (max-width: 800px)

```css

#closeIframe {
    position: fixed; /* Původně mělo hodnotu "absolute", změněno na "fixed" */
    float: right;
    right: 0;
    margin-right: 20px; /* Přidáno pro větší odsazení zprava */
    margin-top: 10px; /* Přidáno pro odsazení zhora */
}
```

A tyto úpravy v souboru **style-form.css:**

```css


#closeIframe {
    z-index: 120;
    position: sticky; /* Původně mělo hodnotu "absolute", změněno na "sticky" */
    float: right;
    right: 0;
    top: 10px; /* Původní hodnota 50px snížena na 10 px */
    margin-left: 20px; /* Změněno z původního "margin" na "margin-left" pro lepší umístění */
    border: none;
    padding: 10px;
    background-color: red !important;
    color: white; 
    border-radius: 10px;
    transition: 0.2s;
}
```
